const ingredients = [
  "Ulei de măsline",
  "Sare",
  "Piper negru",
  "Usturoi",
  "Ceapă",
  "Roșii",
  "Morcovi",
  "Cartofi",
  "Piept de pui",
  "Carne de vită tocată",
  "Ouă",
  "Lapte",
  "Iaurt grecesc",
  "Brânză cheddar",
  "Parmezan",
  "Orez brun",
  "Paste integrale",
  "Quinoa",
  "Linte",
  "Fasole roșie",
  "Fasole albă",
  "Năut",
  "Broccoli",
  "Spanac",
  "Dovlecel",
  "Ardei gras",
  "Castravete",
  "Lămâie",
  "Ghimbir",
  "Oțet balsamic",
  "Mărar",
  "Pătrunjel",
  "Curcan tocat",
  "Somon",
  "Ton (conservă)",
  "Ciuperci",
  "Nuci",
  "Migdale",
  "Semințe de chia",
  "Semințe de in",
  "Fulgi de ovăz",
  "Miere",
  "Banane",
  "Mere",
  "Fructe de pădure",
  "Avocado",
  "Lapte de migdale",
  "Lapte de soia",
  "Făină de ovăz",
  "Făină integrală",
  "Pudră de cacao",
  "Unt de arahide",
  "Sos de soia",
  "Sos de roșii",
  "Drojdie uscată",
  "Zahăr brun",
  "Busuioc",
  "Cimbru",
  "Oregano",
  "Coriandru",
  "Boia dulce",
  "Boia iute",
  "Chimen",
  "Scorțișoară",
  "Cardamom",
  "Turmeric",
  "Chili flakes",
  "Smântână",
  "Creme fraiche",
  "Apă minerală",
  "Apă plată",
  "Unt",
  "Ulei de cocos",
  "Zucchini",
  "Porumb",
  "Mazăre",
  "Rucola",
  "Salată verde",
  "Andive",
  "Ridichi",
  "Fenicul",
  "Praz",
  "Mere verzi",
  "Pere",
  "Portocale",
  "Kiwi",
  "Ananas",
  "Struguri",
  "Curmale",
  "Stafide",
  "Caise uscate",
  "Fulgi de porumb",
  "Musli",
  "Tofu",
  "Tempeh",
  "Laptele de cocos",
  "Făină de migdale",
  "Făină de cocos",
  "Făină albă",
  "Gelatină",
  "Vanilie",
  "Esenta de rom",
  "Apa de trandafiri",
];

module.exports = ingredients;
