module.exports.descriptors = {
  masculin: [
    "Savuros",
    "Picant",
    "Cremuos",
    "Crocant",
    "Sățios",
    "Auriu",
    "Aromat",
    "Delicat",
    "Iute",
    "Afumat",
    "Fraged",
    "Suplu",
    "Rustic",
    "Rapid",
    "Clasic",
    "Dulce",
  ],
  feminin: [
    "Savuroasă",
    "Picantă",
    "Cremuoasă",
    "Crocantă",
    "Sățioasă",
    "Aurie",
    "Aromată",
    "Delicată",
    "Iute", // rămâne la fel
    "Afumată",
    "Fragedă",
    "Suplă",
    "Rustică",
    "Rapidă",
    "Clasică",
    "Dulce", // idem
  ],
};

module.exports.foods = [
  { name: "Paste", gender: "feminin" },
  { name: "Salată", gender: "feminin" },
  { name: "Supă", gender: "feminin" },
  { name: "Curry", gender: "masculin" },
  { name: "Wrap", gender: "masculin" },
  { name: "Tocană", gender: "feminin" },
  { name: "Risotto", gender: "masculin" },
  { name: "Burger", gender: "masculin" },
  { name: "Sote", gender: "neutru" },
  { name: "Smoothie", gender: "neutru" },
  { name: "Tacos", gender: "masculin" },
  { name: "Sandviș", gender: "masculin" },
  { name: "Caserolă", gender: "feminin" },
  { name: "Pizza", gender: "feminin" },
  { name: "Bol cu orez", gender: "masculin" },
  { name: "Omletă", gender: "feminin" },
  { name: "Gratin", gender: "masculin" },
  { name: "Terci", gender: "masculin" },
  { name: "Frigărui", gender: "masculin" },
];
